[package]
distribution = "2201.8.0"
org = "ballerinax"
name = "asb"
version = "3.8.1-SNAPSHOT"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["IT Operations/Message Brokers", "Cost/Paid", "Vendor/Microsoft"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-azure-service-bus"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "org.ballerinax"
artifactId = "asb-native"
module = "asb-native" 
version = "3.8.1-SNAPSHOT"
path = "../native/build/libs/asb-native-3.8.1-SNAPSHOT.jar"
