[package]
distribution = "2201.8.0"
org = "ballerinax"
name = "asb"
version = "3.7.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["IT Operations/Message Brokers", "Cost/Paid", "Vendor/Microsoft"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-azure-service-bus"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "org.ballerinax"
artifactId = "asb-native"
module = "asb-native" 
version = "3.7.0"
path = "../native/build/libs/asb-native-3.7.0.jar"

# Azure dependencies
[[platform.java17.dependency]]
groupId = "com.azure"
artifactId = "azure-messaging-servicebus"
version = "7.17.0"
path = "./lib/azure-messaging-servicebus-7.17.0.jar"

[[platform.java17.dependency]]
groupId = "com.azure"
artifactId = "azure-core"
version = "1.49.0"
path = "./lib/azure-core-1.49.0.jar"

[[platform.java17.dependency]]
groupId = "com.azure"
artifactId = "azure-core-amqp"
version = "2.9.4"
path = "./lib/azure-core-amqp-2.9.4.jar"

# Jackson dependencies
[[platform.java17.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-core"
version = "2.13.5"
path = "./lib/jackson-core-2.13.5.jar"

[[platform.java17.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-annotations"
version = "2.13.5"
path = "./lib/jackson-annotations-2.13.5.jar"

[[platform.java17.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-databind"
version = "@jackson.databind.version@"
path = "./lib/jackson-databind-2.13.5.jar"

[[platform.java17.dependency]]
groupId = "com.fasterxml.jackson.dataformat"
artifactId = "jackson-dataformat-xml"
version = "2.13.5"
path = "./lib/jackson-dataformat-xml-2.13.5.jar"

[[platform.java17.dependency]]
groupId = "com.fasterxml.jackson.datatype"
artifactId = "jackson-datatype-jsr310"
version = "2.13.5"
path = "./lib/jackson-datatype-jsr310-2.13.5.jar"

# Reactive streams dependencies
[[platform.java17.dependency]]
groupId = "org.reactivestreams"
artifactId = "reactive-streams"
version = "1.0.4"
path = "./lib/reactive-streams-1.0.4.jar"

# Project reactor dependencies
[[platform.java17.dependency]]
groupId = "io.projectreactor"
artifactId = "reactor-core"
version = "3.6.6"
path = "./lib/reactor-core-3.6.6.jar"

# Apache proton-j dependencies
[[platform.java17.dependency]]
groupId = "org.apache.qpid"
artifactId = "proton-j"
version = "0.34.1"
path = "./lib/proton-j-0.34.1.jar"
